[package]
name = "tsuki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.3"
miette = "5.10.0"
thiserror = "1.0.51"

[dev-dependencies]
pretty_assertions = "1.4.0"
